config/routes.rb
Rails.application.routes.draw do

    root 'dois#search'
    get 'dois/search'
    get 'dois/reservations'
    post 'dois/reserve'
    post 'dois/unreserve'
    post 'dois/find'
    get 'dois/find'

    post 'dois/search_full_text'

    post 'dois/:id/metadata' => 'dois#edit_metadata_post', as: :edit_metadata
    resources 'dois'

end

app/controllers/dois_controller.rb
require 'uri'
require 'time'
require 'hash_to_html'
require 'research_metadata'
require 'puree'
require 'net/http'
require 'json'

class DoisController < ApplicationController
  include NetHttpHelper
  include Pure

  before_action :load_config

  def reservations
    reservation_summaries = []
    reservations = Reservation.all.order(created_at: :desc)
    reservations.each do |reservation|
      reservation_summary = {}
      reservation_summary['pure_id'] = reservation['pure_id']
      reservation_summary['doi'] = reservation['doi']
      reservation_summary['created_at'] = reservation['created_at']
      reservation_summary['created_by'] = reservation['created_by']
      if reservation.pure_id
        # fetch pure record

        # if dataset
        if reservation.resource_type_id === 1
          extractor = Puree::Extractor::Dataset.new @pure_config
        end

        # if thesis
        if reservation.resource_type_id === 2
          extractor = Puree::Extractor::Thesis.new @pure_config
        end

        metadata_model = extractor.find reservation.pure_id.to_s
        if metadata_model
          summary = pure_summary metadata_model
          reservation_summary['title'] = summary['title']
          reservation_summary['creator'] = summary['creator_name']
        end
      end
      reservation_summaries << reservation_summary
    end
    @reservation_summaries = reservation_summaries
  end

  def search_full_text
    if params[:term]
      @records = Record.search_stuff(params[:term]).with_pg_search_highlight
    end
  end

  def search
    @debug_endpoints = ENV['DEBUG_ENDPOINTS']

    pure_service_error = discover_pure_service_error
    if pure_service_error
      add_service_error pure_service_error
      @pure_up = false
    else
      @pure_up = true
      @pure_version = pure_version
    end

    datacite_service_error = discover_datacite_service_error
    if datacite_service_error
      add_service_error datacite_service_error
      @datacite_up = false
    else
      @datacite_up = true
    end
  end

  def find
    sm = DoiFindStateMachine.new

    pure_resource = determine_pure_resource_from_id params[:pure_id]
    metadata_model = pure_resource['model']

    if metadata_model
      sm.pure_dataset_found
      # logger.info 'Found ' + endpoint
      # logger.info params[:pure_id] +' has DOI ' + has_doi?(response.body).to_s
    else
      sm.pure_dataset_not_found
      # logger.info 'NOT Found ' + endpoint
    end

    if sm.state == 'awaiting_pure_verification'
      redirect_to :back,
                  :flash => { :error => 'Id not found in Pure' }
    end

    @records = Record.where("pure_id = ?", params[:pure_id])

    if @records.empty?
      sm.doi_db_record_not_found
    else
      sm.doi_db_record_found
    end

    @sm_state = sm.state

    if sm.state == 'showing_doi'
      # Using first result only, assuming only one doi for a given pure id
      redirect_to doi_path(id: @records.first.id)
    end

    if sm.state == 'creating_doi'
      summary = pure_summary metadata_model

      if !summary['creator_name']
        flash[:error] = "Minting for #{params[:pure_id]} is not possible as there is no creator defined in Pure"
        redirect_to :back
        return
      end

      if !in_output_whitelist?(summary['output_type'])
        flash[:error] = "It is not possible to mint a DOI for an output of type #{summary['output_type']}"
        redirect_to :back
        return
      end

      summary['pure_id'] = params[:pure_id]
      redirect_to new_doi_path summary

    end

  end

  def index
    @records = Record.all.order(doi_created_at: :desc).paginate(:page => params[:page], :per_page => 10)
    if @records.empty?
      flash[:warning] = 'No records in database for DOIs'
    end
  end

  def new
    pure_id = params[:pure_id]
    if pure_id.empty?
      redirect_to :dois_search
    end
    @reserved_doi = reserved_doi? pure_id
  end

  def edit
    @record = Record.find(params[:id])
    @metadata = get_db_metadata
  end

  def show
    @record = Record.find(params[:id])
    @metadata = get_db_metadata
  end

  def get_db_metadata
    return JSON.parse(@record.metadata)["resource"]
  end

  def create
    sm = DoiCreateStateMachine.new

    pure_id = params[:pure_id]
    output_type = params[:output_type].to_s
    redirect = nil
    db_doi = nil
    db_datacite_metadata = nil
    db_url = nil

    resource_type = get_resource output_type

    minting_from_reservation = false
    reservation = get_reservation(pure_id)
    doi = reservation ? reservation.doi : nil
    minting_from_reservation = true if doi

    if !doi
      next_id = get_resource_type_next_id output_type
      doi_suffix = get_resource_type_doi_name output_type
      path = doi_suffix + '/' + next_id.to_s
      doi = build_doi(identifier: ENV['DATACITE_DOI_IDENTIFIER'],
                      prefix: ENV['DATACITE_DOI_PREFIX'], path: path)
    end
    url = build_url(params[:pure_uuid], params[:title], resource_type.id)

    resource = ENV['DATACITE_ENDPOINT'] + '/doi/' + doi
    username = ENV['DATACITE_USERNAME']
    password = ENV['DATACITE_PASSWORD']

    if remote_doi_minted?(resource, username, password)
      sm.doi_minted
      # do nothing
      flash[:error] = doi + ' already minted'
    else
      sm.doi_not_minted
    end

    if sm.state == 'creating_metadata'
      transformer = create_metadata_transformer output_type
      datacite_metadata = transformer.transform id: pure_id,
                                                doi: doi

      response = create_metadata(datacite_metadata)
      if response.code == '201'
        sm.metadata_created
        flash[:notice] = "#{doi} metadata registered."
        db_doi = doi
        db_datacite_metadata = datacite_metadata
      else
        action = 'register metadata'
        log_msg = "DataCite [#{action}]\n\n#{doi}\n\n#{response.code}\n\n#{response.body}\n\n#{datacite_metadata}"
        flash[:error] = log_msg
        logger.error log_msg
      end
    end

    if sm.state == 'creating_doi'
      response = create_doi(doi, url)
      if response.code == '201'
        sm.doi_created
        # flash[:warning] = "#{url} does not resolve." if !uri_resolves?(url)
        flash[:notice] = "#{doi} registered & associated with #{url}."
        db_url = url
      else
        action = 'register URL'
        log_msg = "DataCite [#{action}]\n\n#{doi}\n\n#{url}\n\n#{response.code}\n\n#{response.body}"
        flash[:error] = log_msg
        logger.error log_msg
      end
    end

    if sm.state == 'minted'
      if minting_from_reservation
        delete_reserved_doi pure_id
        create_metadata_record db_doi, db_datacite_metadata
        create_doi_record db_doi, db_url
      else
        create_metadata_record db_doi, db_datacite_metadata
        create_doi_record db_doi, db_url
        increment_resource_type_count output_type
      end
      redirect = :root
    end

    if flash[:error]
      redirect = :back
    end

    redirect_to redirect

    @sm_state = sm.state
  end

  def uri_resolves?(uri)
    # TO DO
    # Make version that works :)
    uri = URI.parse(uri)
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Get.new(uri)
    response = http.request(req)
    response.code === '404' ? false : true
  end

  def create_doi(doi, url)

    endpoint = ENV['DATACITE_ENDPOINT'] + ENV['DATACITE_RESOURCE_DOI']

    clean_url_path = strip_forward_slashes(url)

    url = clean_url_path

    username = ENV['DATACITE_USERNAME']
    password = ENV['DATACITE_PASSWORD']

    response = create_remote_doi(endpoint, doi, url, username, password)
  end

  def create_doi_record(doi, url)
    now = DateTime.now
    record = Record.find_or_create_by(doi: doi)
    record.doi_created_at = now
    record.doi_created_by = get_user
    record.url = url
    record.url_updated_at = now
    record.url_updated_by = get_user
    record.save
  end

  def claim_reservation(pure_id, resource_type_id)
    reservation = get_cancelled_reservation resource_type_id
    if reservation
      reservation.pure_id = pure_id
      now = DateTime.now
      reservation.created_at = now
      reservation.created_by = get_user
      reservation.save
    end
  end

  def reserve
    pure_id = params[:pure_id]
    output_type = params[:output_type]

    reserved_doi = nil

    resource_type = get_resource output_type
    resource_type_id = normalise_resource_name output_type
    cancelled_reservation = get_cancelled_reservation(resource_type_id)
    if cancelled_reservation
      claim_reservation(pure_id, resource_type_id)
      reservation = Reservation.where(pure_id: pure_id, resource_type_id: resource_type_id).first
      reserved_doi = reservation.doi
    else
      reservation = Reservation.create(pure_id: pure_id)
      next_id = get_resource_type_next_id output_type
      doi_suffix = get_resource_type_doi_name output_type
      path = doi_suffix + '/' + next_id.to_s
      doi = build_doi(identifier: ENV['DATACITE_DOI_IDENTIFIER'],
                      prefix: ENV['DATACITE_DOI_PREFIX'], path: path)
      reservation.doi = doi
      now = DateTime.now
      reservation.created_at = now
      reservation.created_by = get_user
      reservation.resource_type_id = resource_type.id
      if reservation.save
        increment_resource_type_count output_type
      end
      reserved_doi = doi
    end

    flash[:notice] = reserved_doi + ' reserved.'
    redirect_to :root
  end

  def unreserve
    pure_id = params[:pure_id]
    reservation = Reservation.find_by(pure_id: pure_id)
    if reservation
      reservation.pure_id = nil
      now = DateTime.now
      reservation.created_at = now
      reservation.created_by = get_user
      reservation.save
    end

    redirect_to :root
  end

  # to reorganise
  def update
    edit_url_post(params[:id], params[:url])

  end

  def edit_url_post(id, url)
    edit_url(id, url: url, batch_mode: false)
  end

app/helpers/dois_helper.rb
module DoisHelper

end

app/views/dois/_summary.html.erb
<div class="summary">
  <div><h2><%= params[:title] %></h2></div>
  <div><h3><%= params[:creator_name] %></h3></div>
  <div><h4><%= params[:pure_id] %></h4></div>
  <div><h4><%= params[:output_type] %></h4></div>
</div>

app/views/dois/_summary_record.html.erb
<div class="summary">
  <div><h2><%= @metadata['titles']['title'] %></h2></div>
<!--<div><h2><%= @record[:title] %></h2></div>-->
<div><h3>
    <%#= @record[:creator_name] %></h3>
  <% case @metadata['creators']['creator'] %>
  <% when Hash %>
      <%= @metadata['creators']['creator']['creatorName'] %>
  <%  when Array %>
      <ul>
      <% @metadata['creators']['creator'].each do |i| %>
          <li><%= i['creatorName'] %></li>
      <% end %>
      </ul>
  <% end %>
</div>
<div><h4><%= @record[:pure_id] %></h4></div>
<!--<div><h4><%= @record[:pure_uuid] %></h4></div>-->
</div>

app/views/dois/_summary_record_vertical.html.erb
<% @records.each do |record| %>
  <h2><%= record.doi %></h2>
    <%= link_to 'Detail', doi_path(id: record.id), :class => 'pure-button' %>
    <%= link_to 'Edit', edit_doi_path(id: record.id), :class => 'pure-button' %>
  <table class="pure-table pure-table-bordered">
    <tr><td><strong>Pure ID</strong></td><td><%= record.pure_id %></td></tr>
    <!--<tr><td><strong>Pure UUID</strong></td><td><%= record.pure_uuid %></td></tr>-->
    <tr><td><strong>Title</strong></td><td><%= record.title %></td></tr>
    <tr><td><strong>Creators</strong></td>
      <td>
        <%#= record.creator_name %>
        <%#= record.metadata %>
        <% creators = JSON.parse(record.metadata)['resource']['creators']['creator'] %>
        <% case creators %>
        <% when Hash %>
            <%= creators['creatorName'] %>
        <%  when Array %>
            <%= creators[0]['creatorName'] %> et al.
        <% end %>
      </td>
    </tr>
    <tr><td><strong>URL</strong></td><td><%= link_to 'URL', record.url, :target => 'blank' %></td></tr>
    <!--<tr><td><strong>Metadata</strong></td><td><%= raw JSON.parse(record.metadata)['resource'].to_html %></td></tr>-->
  </table>
    <br/>
    <br/>
<% end %>

app/views/dois/_summary_reservation.html.erb
<% if @reservation_summaries.length > 0 %>

    <% @reservation_summaries.each do |reservation| %>
        <h2><%= reservation['doi'] %></h2>
        <% if reservation['pure_id'] %>
            <%= link_to 'Edit', dois_find_path(pure_id: reservation['pure_id']), :class => 'pure-button' %>
        <% end %>
        <table class="pure-table pure-table-bordered">
          <% if reservation['pure_id'] %>
              <tr><td><strong>Pure ID</strong></td><td><%= reservation['pure_id'] %></td></tr>
          <% end %>
          <% if reservation['title'] %>
              <tr><td><strong>Title</strong></td><td><%= reservation['title'] %></td></tr>
          <% end %>
          <% if reservation['creator'] %>
              <tr><td><strong>Creator</strong></td><td><%= reservation['creator'] %></td></tr>
          <% end %>
          <% if reservation['created_at'] %>
              <tr><td><strong>DOI reserved at</strong></td><td><%= reservation['created_at'] %></td></tr>
          <% end %>
          <% if reservation['created_by'] %>
              <tr><td><strong>DOI reserved by</strong></td><td><%= reservation['created_by'] %></td></tr>
          <% end %>
        </table>
        <br/>
        <br/>
    <% end %>

<% else %>
    None
    <br/>
    <br/>
<% end %>

app/views/dois/edit.html.erb
<div class="wrapper">
<%#= @record.inspect %>

<%#= params.inspect %>
  <%= render 'shared/header' %>
<h1><%= @record.doi %></h1>
  <%= link_to 'Detail', doi_path(id: @record.id), :class => 'pure-button' %>
<%= render 'summary_record' %>
<%#= session[:pure_dataset_summary].inspect %>

<%= form_tag(:doi, method: :put, :class => 'pure-form') do %>
    <%#= text_field_tag :pure_id, @record.pure_id, placeholder: 123456,  readonly: false, :required => true, :class => 'text-field-pure-id', hidden: true %>
    <!--DOI:-->
      <%#= text_field_tag :doi, @record.doi, placeholder: 'path/to/resource', readonly: true, :required => true, :class => 'text-field-doi', hidden: true %>
    URL: <%= text_field_tag :url, @record.url, placeholder: 'http://lancaster.ac.uk/path/to/resource', :required => true, :class => 'pure-input-2-3 pure-input-rounded' %>
    <%= submit_tag "Update URL", :class => 'pure-button pure-button-primary' %>
<% end %>

  <br/>
  <br/>

  <div class="metadata-update-atomic">
   <%= form_tag(edit_metadata_path(@record.id)) do %>
      <%= submit_tag "Update metadata", :class => 'pure-button button-secondary' %>
  <% end %>
  </div>
  <br/>
  <br/>
  <%= link_to 'Search', :dois_search, :class => 'pure-button' %>

</div>



<% flash.clear %>

app/views/dois/edit_metadata_batch.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>
  <h1>Metadata update report</h1>
  <% @data.each do |d|  %>
      <div>
      <% if d['updated'] %>
      ERROR --
      <% end %>
      <%= d['record']['pure_id'] %>, <%= d['record']['title'] %>
        </div>
  <% end %>
  <br/>
  <br/>
  <%= link_to 'Search', :dois_search, :class => 'pure-button' %>
  <%= render 'shared/environment' %>
</div>
<% flash.clear %>

app/views/dois/index.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>

  <h1>DOIs</h1>
  <div class="apple_pagination">
    <%= will_paginate @records, :container => false %>
  </div>
  <%#= @sm_state %>
<%#= @headers %>
<%#= params.inspect %>
<%#= @records.inspect %>
    <%#= link_to 'Update all', :batch_update, :class => 'pure-button' %>

<%= render 'summary_record_vertical' %>

  <br>
  <div class="apple_pagination">
    <%= will_paginate @records, :container => false %>
  </div>
  <br>
  <br>
<%= link_to 'Search', :dois_search, :class => 'pure-button' %>
</div>

<% flash.clear %>

app/views/dois/index_horizontal.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>
  <h1>DOIs</h1>
  <%#= @sm_state %>
<%#= @headers %>
<%#= params.inspect %>
<%#= @records.inspect %>

<table border="1" class="pure-table pure-table-horizontal">
  <thead>
  <tr>
    <th>Pure ID</th>
    <th>Pure UUID</th>
    <th>Title</th>
    <th>Creator</th>
    <th>DOI</th>
    <th>URL</th>
    <th>Edit</th>
    <th>Update</th>
    <!--
    <th>Registration Agent</th>
    <th>Resource Type</th>
    <th>DOI Created At</th>
    <th>DOI Created by</th>
    <th>URL Updated At</th>
    <th>URL Updated by</th>
    <th>Metadata Updated At</th>
    <th>Metadata Updated By</th>-->
  </tr>
  </thead>

  <tbody>
  <% @records.each do |record| %>
      <tr>
        <td><%= record.pure_id %></td>
        <td><%= record.pure_uuid %></td>
        <td><%= record.title %></td>
        <td><%= record.creator_name %></td>
        <td><%= record.doi %></td>
        <td><%= record.url %></td>
        <td><%= link_to 'URL', edit_doi_path(id: record.id), :class => 'pure-button' %></td>
        <td>
          <%= form_tag('/dois/' + record.id.to_s + '/metadata/') do %>
              <%= submit_tag "Metadata", :class => 'pure-button pure-button-primary' %>
          <% end %>
        </td>




        <!--
        <td><%= record.doi_registration_agent.name %></td>
        <td><%= record.resource_type.name %></td>
        <td><%= record.doi_created_at %></td>
        <td><%= record.doi_created_by %></td>
        <td><%= record.url_updated_at %></td>
        <td><%= record.url_updated_by %></td>
        <td><%= record.metadata_updated_at %></td>
        <td><%= record.metadata_updated_by %></td>-->
      </tr>
  <% end %>
  </tbody>
</table>
  <br>
  <div class="apple_pagination">
    <%= will_paginate @records, :container => false %>
  </div>

<%#= link_to 'New Account', new_account_path %>
  <br>
  <br>
<%= link_to 'Search', :dois_search, :class => 'pure-button' %>
</div>

<% flash.clear %>

app/views/dois/search.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>

    <h1>Status</h1>
  <%= form_tag({controller: "dois", action: "find"}, method: "post", :class => 'pure-form') do %>
      Pure ID: <%= text_field_tag :pure_id, "", placeholder: 123456, :required => true,
                                  :class => 'pure-input-1-4 pure-input-rounded', type: :number %>
      <%= submit_tag "Search", :class => 'pure-button pure-button-primary', :id => 'search-btn' %>
  <% end %>

  <br/>

  <h1>DOIs</h1>
  <% if ActiveRecord::Base.connection.adapter_name.downcase == 'postgresql' %>
      <p>
        Full-text search for minted DOIs on title, description, keywords, person name, DOI, sizes, file rights and Pure UUID. For example, using   <i>regulat</i> as a word prefix would match the whole words <i>regulate</i>, <i>regulatory</i> and <i>Regulation</i>.
      </p>

      <%= form_tag({controller: "dois", action: "search_full_text"}, method: "post", :class => 'pure-form') do %>
          Word prefix: <%= text_field_tag 'term', params[:term], placeholder: "regulat", :required => true,
                             :class => 'pure-input-1-4 pure-input-rounded' %>
          <%= submit_tag "Search", :class => 'pure-button pure-button-primary', :id => 'search-text-btn' %>
      <% end %>
      <br/>
  <% end %>

  <%= link_to 'DOIs', :dois, :class => 'pure-button' %>
  <%= link_to 'DOI reservations', :dois_reservations, :class => 'pure-button', :id => 'reservations_btn' %>

  <%= render 'shared/status' %>

  <% if @debug_endpoints == 'true' %>
    <%= render 'shared/environment' %>
  <% end %>
</div>

<% flash.clear %>

app/views/dois/search_full_text.html.erb
<!--DEBUG WITH HIGHLIGHTING-->
<%#= params.inspect %>
<%#= @records.inspect %>
<%# @records.each do |record| %>
  <%# if record.respond_to?(:pg_search_highlight) %>
    <%#= record.pg_search_highlight.html_safe %>
  <%# else %>
      <%#= record %>
  <%# end %>
<%# end %>

<div class="wrapper">
  <%= render 'shared/header' %>
  <h1>DOIs</h1>
  <%= render 'summary_record_vertical' %>
  <br>
  <br>
  <%= link_to 'Search', :dois_search, :class => 'pure-button' %>
</div>

<% flash.clear %>

app/views/dois/show.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>

  <%#= @record.inspect %>
  <%#= @metadata.inspect %>

  <h1><%= @record.doi %></h1>
  <%= link_to 'Edit', edit_doi_path(id: @record.id), :class => 'pure-button' %>
  <table class="pure-table pure-table-bordered">
    <%# label_class = 'z-depth-5 light-green lighten-3' %>
    <% label_class = '' %>
    <tr><td class="<%=label_class%>"><strong>Pure ID</strong></td><td><%= @record.pure_id %></td></tr>
    <tr><td class="<%=label_class%>"><strong>Pure UUID</strong></td><td><%= @record.pure_uuid %></td></tr>

    <!--<tr><td><strong>Title</strong></td><td><%= @record.title %></td></tr>-->
    <tr>
      <td class="<%=label_class%>"><strong>Title</strong></td>
      <td>
        <% if @metadata["titles"]["title"].class == String %>
            <%= @metadata["titles"]["title"] %>
        <% end %>
        <% if @metadata["titles"]["title"].class == Array %>
            <% if @metadata["titles"]["title"].size === 1 %><%= @metadata["titles"]["title"][0]%><% end %>
            <% if @metadata["titles"]["title"].size === 2 %><%= @metadata["titles"]["title"][0]%><% end %><% if @metadata["titles"]["title"].size === 2 %>: <%= @metadata["titles"]["title"][1] %><% end %>
        <% end %>
      </td>
    </tr>

    <% if @metadata['descriptions'] %>
        <tr><td class="<%=label_class%>"><strong>Description</strong></td><td><%= @metadata["descriptions"]["description"] %></td></tr>
    <% end %>

    <% if @metadata['subjects'] %>
        <tr>
          <td class="<%=label_class%>"><strong>Keywords</strong></td>
          <td>
            <% case @metadata['subjects']['subject'] %>
            <% when Array %>
                <ul>
                  <% @metadata['subjects']['subject'].each do |i| %>
                      <li>
                        <%= i %>
                      </li>
                  <% end %>
                </ul>
            <% else %>
                <%= @metadata['subjects']['subject'] %>
            <% end %>
          </td>
        </tr>
    <% end %>

    <tr>
      <td class="<%=label_class%>"><strong>Creators</strong></td>
      <td>
        <% creators = @metadata['creators']['creator'] %>
        <% case creators %>
        <% when Hash %>
                <%= creators['creatorName'] %>
        <%  when Array %>
            <%= creators[0]['creatorName'] %> et al.
        <% end %>
      </td>
    </tr>

    <% if @metadata['contributors'] %>
        <tr>
          <td class="<%=label_class%>"><strong>Contributors</strong></td>
          <td>
            <% contributors = @metadata['contributors']['contributor'] %>
            <% case contributors %>
            <% when Hash %>
                <%= contributors['contributorName'] %>
            <%  when Array %>
                <%= contributors[0]['contributorName'] %> et al.
            <% end %>
          </td>
        </tr>
    <% end %>

    <% if @metadata['sizes'] %>
        <tr>
          <td class="<%=label_class%>"><strong>Sizes</strong></td>
          <td>
            <% case @metadata['sizes']['size'] %>
            <% when Array %>
                <ul>
                  <% @metadata['sizes']['size'].each do |i| %>
                      <li>
                        <%= i %>
                      </li>
                  <% end %>
                </ul>
            <% else %>
                <%= @metadata['sizes']['size'] %>
            <% end %>
          </td>
        </tr>
    <% end %>

    <% if @metadata['formats'] %>
        <tr>
          <td class="<%=label_class%>"><strong>Formats</strong></td>
          <td>
            <% case @metadata['formats']['format'] %>
            <% when Array %>
                <ul>
                  <% @metadata['formats']['format'].each do |i| %>
                          <li>
                              <%= i %>
                          </li>
                  <% end %>
                </ul>
            <% else %>
                <%= @metadata['formats']['format'] %>
            <% end %>
          </td>
        </tr>
    <% end %>

    <% if @metadata['rightsList'] %>
        <tr>
          <td class="<%=label_class%>"><strong>Rights</strong></td>
          <td>
            <% case @metadata['rightsList']['rights'] %>
            <% when Array %>
                <ul>
                  <% @metadata['rightsList']['rights'].each do |i| %>
                      <li>
                        <%= i %>
                      </li>
                  <% end %>
                </ul>
            <% else %>
                <%= @metadata['rightsList']['rights'] %>
            <% end %>
          </td>
        </tr>
    <% end %>

<%#= @metadata %>


    <tr><td class="<%=label_class%>"><strong>DOI minted at</strong></td><td><%= @record.doi_created_at %></td></tr>
    <tr><td class="<%=label_class%>"><strong>DOI minted by</strong></td><td><%= @record.doi_created_by %></td></tr>
    <tr><td class="<%=label_class%>"><strong>URL</strong></td><td><%= @record.url %></td></tr>
    <tr><td class="<%=label_class%>"><strong>URL updated at</strong></td><td><%= @record.url_updated_at %></td></tr>
    <tr><td class="<%=label_class%>"><strong>URL updated by</strong></td><td><%= @record.url_updated_by %></td></tr>
    <tr><td class="<%=label_class%>"><strong>Metadata updated at</strong></td><td><%= @record.metadata_updated_at %></td></tr>
    <tr><td class="<%=label_class%>"><strong>Metadata updated by</strong></td><td><%= @record.metadata_updated_by %></td></tr>
  </table>

  <br/>
  <br/>
  <%= link_to 'Search', :dois_search, :class => 'pure-button' %>

</div>

<% flash.clear %>

app/views/dois/update.html.erb
<%= params.inspect %>